[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "1"
path = "src/bin/1.rs"

[lib]
path = "src/lib/lib.rs"

[dependencies]
